# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.4.0
      import:
        # Import only NCS and Zephyr modules required to build Matter samples.
        # Please keep this list sorted alphabetically.
        name-allowlist:
          # NCS projects
          - bme68x
          - bsec
          - coremark
          - doc-internal
          - dragoon
          - find-my
          - hostap
          - libmodem
          - matter
          - mbedtls
          - mcuboot
          - nrf-802154
          - nrf_wifi
          - nrfxlib
          - oberon-psa-crypto
          - openthread
          - psa-arch-tests
          - qcbor
          - t_cose
          - trusted-firmware-m
          - zephyr
          # Zephyr modules (imported via nrf/west.yml zephyr name-allowlist)
          - cmsis
          - cmsis_6
          - hal_nordic
          - libmetal
          - lz4
          - open-amp
          - picolibc
          - tf-psa-crypto
          - zcbor
    - name: matter
      remote: ncs
      path: modules/lib/matter
      repo-path: sdk-connectedhomeip
      revision: ncs-matter-v1.0.0
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: pigweed
          path: third_party/pigweed/repo
        - name: jsoncpp
          path: third_party/jsoncpp/repo
        - name: uriparser
          path: third_party/uriparser/repo
      userdata:
        ncs:
          upstream-url: https://github.com/project-chip/connectedhomeip
          upstream-sha: badaac1eae0df6902c1d009981c0e0d18845aeea
          compare-by-default: false

  self:
    path: ncs-matter
    west-commands: scripts/west/west-commands.yml
