# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: 8a3adfcc385686b1764ff4a3e1c37df0036cde3f
      import: true
    - name: matter
      remote: ncs
      path: modules/lib/matter
      repo-path: sdk-connectedhomeip
      revision: ce40acb6eb3405f92e0f451c87732a6639a634df
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: pigweed
          path: third_party/pigweed/repo
        - name: jsoncpp
          path: third_party/jsoncpp/repo
        - name: uriparser
          path: third_party/uriparser/repo
      userdata:
        ncs:
          upstream-url: https://github.com/project-chip/connectedhomeip
          upstream-sha: badaac1eae0df6902c1d009981c0e0d18845aeea
          compare-by-default: false

  self:
    path: ncs-matter
    west-commands: scripts/west/west-commands.yml
