#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Install ncs-matter's pigweed_environment.gni stub into the Matter module tree
# so GN can run without Matter bootstrap.

function(ncs_matter_install_pigweed_environment_gni)
  if(NOT CONFIG_CHIP)
    return()
  endif()

  if(NOT ZEPHYR_CONNECTEDHOMEIP_MODULE_DIR OR NOT ZEPHYR_NCS_MATTER_MODULE_DIR)
    message(WARNING
      "ncs-matter: skipping pigweed_environment.gni install because Matter or "
      "ncs-matter module paths are unavailable.")
    return()
  endif()

  set(pw_env_gni_src "${ZEPHYR_NCS_MATTER_MODULE_DIR}/cmake/pigweed_environment.gni")
  set(pw_env_gni_dest_dir "${ZEPHYR_CONNECTEDHOMEIP_MODULE_DIR}/build_overrides")
  set(pw_env_gni_dest "${pw_env_gni_dest_dir}/pigweed_environment.gni")

  if(NOT EXISTS "${pw_env_gni_src}")
    message(FATAL_ERROR
      "ncs-matter: missing pigweed_environment.gni stub at ${pw_env_gni_src}")
  endif()

  file(MAKE_DIRECTORY "${pw_env_gni_dest_dir}")

  if(EXISTS "${pw_env_gni_dest}")
    file(READ "${pw_env_gni_dest}" pw_env_gni_existing)
    file(READ "${pw_env_gni_src}" pw_env_gni_expected)

    if(NOT pw_env_gni_existing STREQUAL pw_env_gni_expected)
      message(WARNING
        "ncs-matter: replacing ${pw_env_gni_dest} with the ncs-matter stub. "
        "The existing file differs (for example, it may have been generated by "
        "Matter bootstrap.sh). Run bootstrap again after the build if you need "
        "the bootstrap-generated Pigweed environment for host GN tooling.")
    else()
      return()
    endif()
  endif()

  file(COPY "${pw_env_gni_src}" DESTINATION "${pw_env_gni_dest_dir}")
endfunction()

ncs_matter_install_pigweed_environment_gni()
